# Generated by Django 5.2.10 on 2026-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ECOMMERCE", "E-commerce"),
                            ("VIDEO", "Video"),
                            ("REVIEW", "Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
