# Generated by Django 5.0.6 on 2026-02-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COLLECTED", "Collected"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="products.product",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_sources",
                        to="products.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("HTML", "HTML"),
                            ("TEXT", "Text"),
                            ("JSON", "JSON"),
                            ("TRANSCRIPT", "Transcript"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("FETCHED", "Fetched"), ("FAILED", "Failed")],
                        default="FETCHED",
                        max_length=20,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_data",
                        to="products.productsource",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="productsource",
            constraint=models.UniqueConstraint(
                fields=("product", "source"), name="unique_product_source"
            ),
        ),
    ]
