# Generated by Django 5.2.10 on 2026-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_insight"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawdata",
            name="source_identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
