# Generated by Django 5.2.10 on 2026-03-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_rawdata_source_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
