# Generated by Django 5.2.10 on 2026-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_source_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
