# Generated by Django 5.2.10 on 2026-03-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_source_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawdata",
            name="content",
            field=models.JSONField(),
        ),
    ]
