from django.db import models

class Product(models.Model):
    class Status(models.TextChoices):
        CREATED = "CREATED", "Created"
        COLLECTING = "COLLECTING", "Collecting"
        ANALYZING = "ANALYZING", "Analyzing"
        READY = "READY", "Ready"
        FAILED = "FAILED", "Failed"

    query = models.CharField(max_length=255)

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.CREATED,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Optional for now — can be removed or kept nullable
    user = models.ForeignKey(
        "auth.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.query} [{self.status}]"
    
class Source(models.Model):
    #id is auto-generated by Django as primary key 
    class SourceType(models.TextChoices):
        ECOMMERCE = "ECOMMERCE", "E-commerce"
        VIDEO = "VIDEO", "Video"
        REVIEW = "REVIEW", "Review"

    name = models.CharField(max_length=100, unique=True)

    type = models.CharField(
        max_length=20,
        choices=SourceType.choices
    )

    code = models.CharField(max_length=50, unique=True) 

    base_url = models.URLField(blank=True, null=True)

    is_active = models.BooleanField(default=True) # To enable/disable source without deleting it

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class ProductSource(models.Model):
    #this model is a join between Product and Source, it represents a specific URL from a source for a product query
    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["product", "source"],
                name="unique_product_source"
            )
        ]
    #this class ensures that for a given product and source, there can only be one entry in the ProductSource table
    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        COLLECTED = "COLLECTED", "Collected"
        FAILED = "FAILED", "Failed"

    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="sources",
    )

    source = models.ForeignKey(
        Source,
        on_delete=models.CASCADE,
        related_name="product_sources",
    )

    url = models.URLField()

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product} → {self.source}"

class RawData(models.Model):

    class DataType(models.TextChoices):
        HTML = "HTML", "HTML"
        TEXT = "TEXT", "Text"
        JSON = "JSON", "JSON"
        TRANSCRIPT = "TRANSCRIPT", "Transcript"


    class Status(models.TextChoices):
        FETCHED = "FETCHED", "Fetched"
        FAILED = "FAILED", "Failed"


    product_source = models.ForeignKey(
        ProductSource,
        on_delete=models.CASCADE,
        related_name="raw_data",
    )


    source_identifier = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )


    data_type = models.CharField(
        max_length=20,
        choices=DataType.choices,
    )


    content = models.JSONField()


    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.FETCHED,
    )


    fetched_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.product_source} [{self.data_type}]"
    
class Insight(models.Model):
    product = models.OneToOneField(
        Product,
        on_delete=models.CASCADE,
        related_name="insight",
    )

    content = models.JSONField()
    # example:
    # {
    #   "pros": [...],
    #   "cons": [...],
    #   "common_complaints": [...],
    #   "verdict": "..."
    # }

    generated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Insight for {self.product}"


